fix: updates extensionSDK and bumps timeout to 500s
looker-open-source/app-data-dictionary pull request #51
Opened 2021-05-06 21:46 UTC by noahamac

Had to make some updates to get `chattyTimeout` on the ExtensionProvider

Updated broken tests, re-linted

2021-05-06 21:47 UTC, noahamac commented on src/components/DataDictionary.tsx
> +    // eslint-disable-next-line react/display-name
Bleh!

Looks like eslint doesn't like these formatter functions. Another reason to refactor this functionality

2021-05-06 23:00 UTC, bryans99 requested changes
Referencing 3.1 methods.

Smaller PRs! This could have been 2 I think

2021-05-06 23:00 UTC, bryans99 commented on src/utils/queries.ts
> +} from '@looker/sdk/lib/3.1/models'
Should be from 4.0. You are using LookerSDK40

2021-05-06 23:00 UTC, bryans99 commented on src/utils/queries.ts
> +import { Looker31SDK as LookerSDK } from '@looker/sdk/lib/3.1/methods'
Ditton

2021-05-06 23:00 UTC, bryans99 commented on src/utils/urls.ts
> +} from '@looker/sdk/lib/3.1/models'
4.0

2021-05-24 23:00 UTC, noahamac commented
Resolved by https://github.com/looker-open-source/app-data-dictionary/pull/56

2021-05-24 23:00 UTC, closed without merging